### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Mr-ARIYA** [drubicza/python_pyc_re_files#1]
Cara decompile marshall zlib base64 ;) Saya kasih Pulsa serius, Minta no WA atau Chat saya di https://wa.me/6282322405139 Thanks;)

**Comment by drubicza** [comment]
Mana sourcenya?

**Comment by Mr-ARIYA** [comment]
Berbentuk File, Chat WA aja om --> 082322405139

**Comment by Mr-ARIYA** [comment]
Saya udah ada File nya, tapi gunain nya gimana kalo mau decompile??

**Comment by Mr-ARIYA** [comment]
Mohon bantuan nya ;(

**Comment by drubicza** [comment]
Maaf, saya ga bisa bantu kalau harus chat WA.
